Hackathon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Hackathon.Entities;

namespace Hackathon.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Leaderboard(bool isPrivate = false, bool isTotal = false)
        {
            ViewBag.isPrivate = isPrivate;
            ViewBag.isTotal = isTotal;
            return View();
        }

        /*[Authorize(Roles = "admin")]
        public ActionResult LeaderboardPrivate()
        {
            return View();
        }*/

        public ActionResult Over()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Hackathon/Controllers/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Threading.Tasks;
using Hackathon.Models;
using Hackathon.Entities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Deedle;

namespace Hackathon.Controllers
{
    public class ScoreResult
    {
        public enum ScoreResultType
        {
            Ok,
            Error
        }

        public ScoreResultType Type;
        public double Score;
        public List<string> Errors;
    }

    public class SolutionsController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Solutions()
        {
            List<Solution> model = new List<Solution>();
            return View(model);
        }

        [Authorize]
        public ActionResult Submit()
        {
            //if (DateTime.UtcNow > new DateTime(2017,6,29,14,45,0,DateTimeKind.Utc))
              //  return RedirectToAction("Over","Home");
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Submit(SubmissionModel model)
        {
            //if (DateTime.UtcNow > new DateTime(2017, 6, 29, 14, 45, 0, DateTimeKind.Utc))
            //    return RedirectToAction("Over", "Home");

            if (!ModelState.IsValid)
            {
                //ScoreResult error = new ScoreResult();
                //error.Errors = new List<string>();

                return View("Submit");
            }

            
            using (var db = new HackathonContext())
            {
                Solution sub = new Solution();
                sub.SubmissionId = Guid.NewGuid();
                sub.Title = model.Title;
                if (Request.IsAuthenticated)
                {
                    sub.UserName = User.Identity.Name;
                }
                else
                    sub.UserName = "TestUser";

                using (var ms = new FileStream($"{SubmissionsPath}{sub.SubmissionId}.csv",FileMode.Create, FileAccess.Write))
                {
                    await model.SolutionFile.InputStream.CopyToAsync(ms);
                }

                //Task.Run(() => model.SolutionFile.InputStream.SaveAs($"{SubmissionsPath}{sub.SubmissionId}.csv"));

                ScoreResult scoreResult;

                scoreResult = Task.Run(() => Score(sub.SubmissionId, true)).Result;
                if (scoreResult.Type != ScoreResult.ScoreResultType.Ok)
                    return View("SubmissionError", scoreResult);
                sub.ScorePublic = scoreResult.Score;

                scoreResult = Task.Run(() => Score(sub.SubmissionId, false)).Result;
                if (scoreResult.Type != ScoreResult.ScoreResultType.Ok)
                    return View("SubmissionError", scoreResult);
                sub.ScorePrivate = scoreResult.Score;

                sub.Submited = DateTime.UtcNow.AddHours(3);

                db.Solutions.Add(sub);
                db.SaveChanges();
            }

            return RedirectToAction("Leaderboard", "Home");
        }

        public ActionResult Leaderboard(bool isPrivate = false, bool isTotal = false)
        {
            using (var db = new HackathonContext())
            {
                LeaderboardModel model = new LeaderboardModel();
                isPrivate = isPrivate && User.IsInRole("admin");
                isTotal = isPrivate && isTotal;
                model.IsPrivate = isPrivate;
                model.IsTotal = isTotal;
                model.Items = db.Solutions.GroupBy(g=>g.UserName)
                                            .Select(g => new {
                                                UserName = g.Key,
                                                Solution = g.OrderByDescending(s => (isPrivate ? (isTotal ? s.ScorePublic*0.2 + s.ScorePrivate*0.8 : s.ScorePrivate) : s.ScorePublic)).FirstOrDefault(),
                                                SubmissionsCount = g.Count()
                                            })
                                            .OrderByDescending(s => (isPrivate ? 
                                                        (isTotal ? 
                                                            s.Solution.ScorePrivate*0.8 + s.Solution.ScorePublic*0.2 : 
                                                            s.Solution.ScorePrivate) : 
                                                        s.Solution.ScorePublic))
                                            .ToList()
                                            .Select(s => {
                                                var user = UserManager.FindByNameAsync(s.UserName).Result;
                                                LeaderboardItemModel li = new LeaderboardItemModel()
                                                {
                                                    UserName = s.UserName,
                                                    Surname = user?.Surname,
                                                    Name = user?.Name,
                                                    TerBank = user?.TerBank.ToString(),
                                                    ScorePublic = s.Solution.ScorePublic,
                                                    ScorePrivate = s.Solution.ScorePrivate,
                                                    ScoreTotal = s.Solution.ScorePublic*0.2 + s.Solution.ScorePrivate*0.8,
                                                    Submited = s.Solution.Submited,
                                                    Title = s.Solution.Title,
                                                    SubmissionsCount = s.SubmissionsCount
                                                };
                                                return li;
                                            })
                                            .ToList();
                //if (isPrivate)
                //    return View("LeaderboardPrivate", model);
                //else
                    return View(model);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult LeaderboardTB(bool isTotal = false)
        {
            using (var db = new HackathonContext())
            {
                LeaderboardTBModel model = new LeaderboardTBModel();
                bool isPrivate = true;
                //bool isTotal = true;
                /*model.IsPrivate = isPrivate;
                model.IsTotal = isTotal;*/
                var lbUsers = db.Solutions.GroupBy(g => g.UserName)
                                            .Select(g => new {
                                                UserName = g.Key,
                                                Solution = g.OrderByDescending(s => (isPrivate ? (isTotal ? s.ScorePublic * 0.2 + s.ScorePrivate * 0.8 : s.ScorePrivate) : s.ScorePublic)).FirstOrDefault(),
                                                SubmissionsCount = g.Count()
                                            })
                                            .OrderByDescending(s => (isPrivate ?
                                                        (isTotal ?
                                                            s.Solution.ScorePrivate * 0.8 + s.Solution.ScorePublic * 0.2 :
                                                            s.Solution.ScorePrivate) :
                                                        s.Solution.ScorePublic))
                                            .ToList()
                                            .Select(s => {
                                                var user = UserManager.FindByNameAsync(s.UserName).Result;
                                                LeaderboardItemModel li = new LeaderboardItemModel()
                                                {
                                                    UserName = s.UserName,
                                                    Surname = user?.Surname,
                                                    Name = user?.Name,
                                                    TerBank = user?.TerBank.ToString(),
                                                    ScorePublic = s.Solution.ScorePublic,
                                                    ScorePrivate = s.Solution.ScorePrivate,
                                                    ScoreTotal = s.Solution.ScorePublic * 0.2 + s.Solution.ScorePrivate * 0.8,
                                                    Submited = s.Solution.Submited,
                                                    Title = s.Solution.Title,
                                                    SubmissionsCount = s.SubmissionsCount
                                                };
                                                return li;
                                            })
                                            .ToList();

                model.Items = lbUsers.GroupBy(g => g.TerBank)
                                    .Select(g => new LeaderboardBaseItemModel()
                                    {
                                        TerBank = g.Key,
                                        ScorePublic = g.Average(u => u.ScorePublic),
                                        ScorePrivate = g.Average(u => u.ScorePrivate),
                                        ScoreTotal = g.Average(u => u.ScorePublic*0.2) + g.Average(u => u.ScorePrivate*0.8),

Hackathon/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hackathon/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hackathon/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="jumbotron">
    <h1>Internal Audit Data Science Day<br />Hackathon</h1>
    <p class="lead">Хакатон по анализу данных УВА ПАО "Сбербанк"</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-sm-12">
        <div>
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#task" aria-controls="task" role="tab" data-toggle="tab">Задание</a></li>
                <li role="presentation"><a href="#metric" aria-controls="metric" role="tab" data-toggle="tab">Метрика</a></li>
                <li role="presentation"><a href="#data" aria-controls="data" role="tab" data-toggle="tab">Данные</a></li>
                <li role="presentation"><a href="#baseline" aria-controls="baseline" role="tab" data-toggle="tab">Baseline</a></li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="task">
                    <p></p>
                    <p>Данные содержат транзакции по кредитным картам в течение 2 дней сентября 2013 года европейскими держателями карт. Часть транзакций являются мошенническими. Особенностью датасета является несбалансированность классов.</p>
                    <p>Датасет содержит только числовые входные переменные, которые являются результатом преобразования PCA, что обусловлено необходимостью анонимизации данных: V1, V2, ... V28. Единственными непреобразованными параметрами являются “Time” и “Amount”.</p>
                    <p>Time – количество секунд, прошедших с начала наблюдения до текущей транзакции.</p>
                    <p>Class - принимает значение 1 в случае мошенничества и 0 в противном случае.</p>
                    <p>Задача - определить мошеннические транзакции для тестовой выборки.</p>
                    @*<p>Датасет создан во время исследовательского проекта Worldline и Machine Learning Group (http://mlg.ulb.ac.be) ULB (Université Libre de Bruxelles). Более подробную информацию о текущих и прошлых проектах по смежным темам можно найти на <a target="_blank" href="http://mlg.ulb.ac.be/BruFence">http://mlg.ulb.ac.be/BruFence</a> и <a href="http://mlg.ulb.ac.be/ARTML" target="_blank">http://mlg.ulb.ac.be/ARTML</a></p>
                    <p>Для цитирования: Andrea Dal Pozzolo, Olivier Caelen, Reid A. Johnson and Gianluca Bontempi. Calibrating Probability with Undersampling for Unbalanced Classification. In Symposium on Computational Intelligence and Data Mining (CIDM), IEEE, 2015</p>*@
                </div>
                <div role="tabpanel" class="tab-pane" id="metric">
                    <p></p>
                    <p>В качестве метрики качества решения используется F1:</p>
                    <p>F1 = 2 * (precision * recall) / (precision + recall)</p>
                </div>
                <div role="tabpanel" class="tab-pane" id="data">
                    <p></p>
                    <p><a href="@Url.Content("~/Content/Datasets/dataset_train.csv")" target="_blank">Train</a></p>
                    <p><a href="@Url.Content("~/Content/Datasets/dataset_test.csv")" target="_blank">Test</a></p>
                    <p><a href="@Url.Content("~/Content/Datasets/sample_submission.csv")" target="_blank">Sample submission</a></p>
                </div>
                <div role="tabpanel" class="tab-pane" id="baseline">
                    <p></p>
                    <p>В качестве baseline-решения предлагается логистическая регрессия.</p>
                    <p>Публичный F1 = 0.706</p>
                    <p><a href="@Url.Content("~/Content/Notebooks/baseline.ipynb")" target="_blank">Baseline.ipynb</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
    @*<div class="row">
        <div class="col-sm-12">
            <a href="@Url.Action("Submit", "Solutions")" class="btn btn-success">Направить решение</a>
        </div>
    </div>

    @{Html.RenderAction("Leaderboard", "Home");}*@

@*
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

Hackathon/Views/Home/Leaderboard.cshtml
@{
    ViewBag.Title = "Leaderboard";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

@{Html.RenderAction("Leaderboard", "Solutions", new { isPrivate = ViewBag.isPrivate, isTotal = ViewBag.isTotal });}

Hackathon/Views/Home/LeaderboardPrivate.cshtml
@{
    ViewBag.Title = "Leaderboard";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

@{Html.RenderAction("LeaderboardPrivate", "Solutions");}

Hackathon/Views/Home/Over.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="alert alert-info">
    <h1>Хакатон is over!</h1>
    <h3>Спасибо за участие.</h3>
</div>